# Generated by Django 5.0.1 on 2024-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='workshop.product'),
        ),
    ]
