from .auth_views import *
from .employee_views import *
from .service_views import *
from .product_views import *
from .client_views import *
from .work_order_views import *
from .reservation_views import *
from .public_reservation_views import *
from .inventory_views import *
from .home_views import *
from .auth_views import *
from .client_views import *
from .service_views import *
from .work_order_views import *
from .admin_reservation_views import *
from .client_reservation_views import *